### ISSUE TITLE
user-defined types are always global

### ISSUE THREAD

**Issue by jinchengJL** [anachromeJ/harmonica#4]
currently typedef statements are only allowed in local scope, but they are considered global. doesn't make sense. changing this may require significant ast change.

**Comment by guihao-liang** [comment]
Do you think it's the problem of AST? I think it's the matter of code gen and type checker. When you use typedef in local scope, then it should be only valid locally. When reaching the end of this scope, the memory for the local var should be released.

**Comment by hiemal** [comment]
I agree that this is of codegen but ast.

**Comment by jinchengJL** [comment]
Our AST only allows typedef statements in local scope. I think we should at least allow it in global scope (and maybe even disallow in local scope). Does it make sense to have new types defined in a local scope?

Also there is no local variable involved. I'm only referring to new types, not actual variables.

**Comment by guihao-liang** [comment]
I see your point. It's like C way of doing this. But we don't have concept of extern var, so local typedef is fine. If you want your typedef visible globally, you can put it at very beginning of main().
